name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-docker-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: '1.18.x'

      - uses: actions/checkout@v1

      - name: Docker Build
        working-directory: .
        run: docker build . --file Dockerfile --tag idp-app:latest

      - name: Docker Tag Release
        run: |
          TAG=$(git rev-parse --short HEAD)
          docker tag idp-app:latest jonathan99/idp-app:$TAG

      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Docker Push Latest
        working-directory: idp-app
        run: docker push jonathan99/idp-app:latest

      - name: Docker Push Release Tag
        working-directory: idp-app
        run: |
          TAG=$(git rev-parse --short HEAD)
          docker push jonathan99/idp-app:$TAG
    
